In [1]:
import torch
torch.__version__

'2.3.1+cu118'

In [2]:
scalar = torch.tensor(3.14159)
print(scalar)

tensor(3.1416)


In [3]:
scalar.item()

3.141590118408203

In [4]:
# matrix
matrix = torch.tensor([[0, 1], [2, 3], [4, 5]])
print(matrix)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [5]:
matrix.ndim

2

In [6]:
matrix.shape

torch.Size([3, 2])

In [7]:
# 3D tensor
tensor = torch.tensor([[[0, 1], [2, 3]], [[4, 5], [6, 7]], [[8, 9], [10, 11]]])
tensor.shape, tensor.ndim

(torch.Size([3, 2, 2]), 3)

In [8]:
random_tensor = torch.rand(3, 4)
print(random_tensor)
random_tensor.dtype

tensor([[0.8664, 0.4774, 0.9736, 0.0954],
        [0.6907, 0.5180, 0.5198, 0.5657],
        [0.0286, 0.8395, 0.7940, 0.5453]])


torch.float32

In [9]:
# create a tensor of zeros
zeros_tensor = torch.zeros(3, 4)
print(zeros_tensor)

# create a tensor of ones
ones_tensor = torch.ones(3, 4)
print(ones_tensor)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [11]:
zero_to_nine = torch.arange(10)
print(zero_to_nine) 

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
